<a href="https://colab.research.google.com/github/SoundaryaSarathi/MLCodes/blob/main/linearreg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#linear regression using gradient descent
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
import matplotlib.pyplot as plt

In [ ]:
class Linreg: 
    def __init__(self,n_features,n_samples,learning_rate=0.01,n_iters=1000):
        self.lr = learning_rate
        self.n_samples=n_samples
        self.n_features=n_features 
        self.n_iters = n_iters
        self.weights = np.zeros((1,n_features))
        self.bias = 0 
    
    def y_predict(self,x):
        return np.dot(self.weights,x.T)+self.bias
    
    def gradientdescent(self,x,error):
        dw=(1/self.n_samples)*np.dot(error,x)
        #print('dw:',dw,dw.shape)
        db=(1/self.n_samples)*np.sum(error)
        return dw,db
        
    def updateparam(self,dw,db):
        self.weights-=self.lr*dw
        self.bias-=self.lr*db
   
    def fit(self,x,y):
      cost_list=[]
      for i in range(self.n_iters):
        y_predict=self.y_predict(x)
        error=y_predict-y
        cost=(1/2*self.n_samples)*(np.sum(np.square(error)))
        dw,db=self.gradientdescent(x,error)
        self.updateparam(dw,db)
        cost_list.append(cost)
      return cost_list

 

In [ ]:
#generation
x,y=datasets.make_regression(n_samples=100,n_features=2,noise=5)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=123)

#normalize(x_train)
#plotting
#fig=plt.figure()
#ax = plt.axes(projection ="3d")
#ax.scatter3D(x_train[:,0],x_train[:,1],y_train)
#plt.scatter(x_train,y_train)
#plt.show()

n_samples,n_features=x_train.shape
print('y_train:',y_train)
linreg=Linreg(n_features,n_samples,0.1,100)
cost_list=linreg.fit(x_train,y_train)
print('costlist: ',cost_list)
print("weights,bias:",linreg.weights,linreg.bias)



y_train: [  33.75341022   77.79638714   32.78841903   17.89671006    7.78115908
   20.33035214   50.24173094   -9.64469725  -51.19595185  -11.633483
    7.62358186  -28.59030673  -15.41708481   61.99772237  127.96906374
   -4.4298641     2.75037467  -84.48799236   -0.96201682   72.63508877
  -45.49353392   51.34235574    6.03524306    5.7851318    67.55145157
   37.68878097 -104.54542243  135.55634188  -19.41593803   84.55621428
  -70.33955858  -33.24401489   48.16225341  -93.69410547  -19.44802535
  -65.94189721  -52.60608599   -6.96194052   57.66339667  -61.42257999
  119.09968375  146.97400481   -6.83504732 -146.21598737  -36.35033509
   18.43315097   -3.58567539   10.53828021  -60.30734421  -69.92396168
  -92.96264155 -177.63325107   54.61577711  -78.58437861  -97.77680865
 -110.51433495  -76.54058626  -16.48703319  -14.83865548  -55.11559075
   46.56851493   32.6710498   159.6819996    46.41520168   19.2732512
  -52.67253371   24.96226667  -85.92391682  -35.52315849   14.29486504


In [ ]:

#illustrating addition of vector to a scalar
w=np.array([[1,1],[2,2]])
z=w+3
print(z)



[[4 4]
 [5 5]]


In [ ]:
import numpy as np
a = np.array([5,4])[np.newaxis]
print(a)
print(a.T)


[[5 4]]
[[5]
 [4]]
